(module
  (memory $private (import "cap" "private_memory") 1 32768 shared)
  (memory $global (import "cap" "global_memory") 1 16384 shared)
  (memory $scoped (import "cap" "scoped_memory") 1 16384 shared)

  (func (export "store_private") (param i32 i32)
    (i32.store $private (local.get 0) (local.get 1)))
  (func (export "load_private") (param i32) (result i32)
    (i32.load $private (local.get 0)))
  (func (export "store_global") (param i32 i32)
    (i32.store $global (local.get 0) (local.get 1)))
  (func (export "load_global") (param i32) (result i32)
    (i32.load $global (local.get 0)))
  (func (export "load_scoped") (param i32) (result i32)
    (i32.load $scoped (local.get 0)))
  (func (export "copy_global_to_private") (param i32 i32 i32)
    (memory.copy $private $global (local.get 0) (local.get 1) (local.get 2)))
  (func (export "copy_private_to_scoped") (param i32 i32 i32)
    (memory.copy $scoped $private (local.get 0) (local.get 1) (local.get 2)))
  (func (export "atomic_add_global") (param i32 i32) (result i32)
    (i32.atomic.rmw.add $global (local.get 0) (local.get 1)))
  (func (export "notify_global") (param i32 i32) (result i32)
    (memory.atomic.notify $global (local.get 0) (local.get 1)))
  (func (export "grow_private") (param i32) (result i32)
    (memory.grow $private (local.get 0)))
  (func (export "size_private") (result i32) (memory.size $private))
  (func (export "size_scoped") (result i32) (memory.size $scoped))
)
