// Generated by pglite-generate-extension-wrapper. Do not edit.
import type { PGliteExtensionBackendDescriptor } from '@electric-sql/pglite'

export const generatedExtensionBackend = {
  releaseProfile: 'wasm32-initial',
  targetKeys: ['wasm32-classic', 'wasm32-multi-memory'],
  artifacts: {
    'wasm32-classic': {
      targetKey: 'wasm32-classic',
      target: {
        pointerWidth: 32,
        memoryAddressWidth: 32,
        topology: 'classic',
        postgresMajor: 18,
        postgresAbi:
          'postgres-180003-catalog-202506291-block-8192-wal-8192-wasm32',
        pgliteExtensionAbi: 'pglite-extension-abi-v1',
        memoryAbi: 'pglite-classic-memory-v1',
        hostAbi: 'pglite-host-abi-v1',
      },
      archiveBytes: 49657,
      archiveSha256:
        'e5110423a925f63f75f2063c38e1604bfc530522c3f314c995425f75ef7d8b84',
      manifestSha256:
        '70825714c678291ab386cb1dfef68bca1e23e19b3aef0f50266eec10b0c57556',
      manifest: {
        formatVersion: 1,
        extensionName: 'vector',
        extensionVersion: '0.0.5',
        target: {
          pointerWidth: 32,
          memoryAddressWidth: 32,
          topology: 'classic',
          postgresMajor: 18,
          postgresAbi:
            'postgres-180003-catalog-202506291-block-8192-wal-8192-wasm32',
          pgliteExtensionAbi: 'pglite-extension-abi-v1',
          memoryAbi: 'pglite-classic-memory-v1',
          hostAbi: 'pglite-host-abi-v1',
        },
        artifactDependencies: [],
        postgresExtensions: [
          {
            name: 'vector',
            requires: [],
          },
        ],
        files: [
          {
            path: 'include/postgresql/server/extension/vector/halfvec.h',
            size: 2031,
            sha256:
              'f32099b56688fbae57548083a26555fafb296e0bf68430c368cf8e5d61e8daf2',
            kind: 'other',
          },
          {
            path: 'include/postgresql/server/extension/vector/sparsevec.h',
            size: 1184,
            sha256:
              'e58587d476df10bfbed2c63cfd50a91d7e8067f9d180c650b9d5990d2f6a82f6',
            kind: 'other',
          },
          {
            path: 'include/postgresql/server/extension/vector/vector.h',
            size: 825,
            sha256:
              '5dd5f55ae4dab6b950e2274ef50c69c2ddc1263f019d647630bf3bfa57f493a3',
            kind: 'other',
          },
          {
            path: 'lib/postgresql/vector.so',
            size: 100191,
            sha256:
              'b96fce0b884ca5bcb85b7a2b759c2debebce760f996c3c014097c5755d96e4a2',
            kind: 'side-module',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.0--0.1.1.sql',
            size: 2047,
            sha256:
              '7b98ca899d63e8128ea3c980634b2d675e0dc6e7f27843e666d4e9980db0ab63',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.1--0.1.3.sql',
            size: 153,
            sha256:
              '57024ba8abad34b9ca151310748518b061a36e2df9b5ba0487e1cd186b1a208f',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.3--0.1.4.sql',
            size: 153,
            sha256:
              '98e7caa4958e026c56613ed779abe469adca9e5e82190d20e19aa345c5e6f71f',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.4--0.1.5.sql',
            size: 153,
            sha256:
              '3fa555492b673f9e0402fefdbd3fc0e479afb29b7141b49145bed8dc691b2c4f',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.5--0.1.6.sql',
            size: 153,
            sha256:
              '557e3d9df2b9f5a5a2428545dbcfa7d99d62f489bbd44127445a36663a8953d1',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.6--0.1.7.sql',
            size: 403,
            sha256:
              '0975ff29e6b8268382253ce0e75cc6b5364582280ef1a7b40a137ce4c6267887',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.7--0.1.8.sql',
            size: 396,
            sha256:
              'fcac329c0901fdcb1d3884e7bf8017c75632136dea88fb8b6352de7e61d4aba5',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.8--0.2.0.sql',
            size: 153,
            sha256:
              'ac330285f527a73d4def55b5de17eae6729a0c052139bb0345aa1a92af96d516',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.0--0.2.1.sql',
            size: 744,
            sha256:
              '0ccec7b1bc7c5e76f5da10b06713e45b08aebcdca7c833ffb4fda8f44d7ae872',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.1--0.2.2.sql',
            size: 153,
            sha256:
              '79a1492abf44c7641893b9f80ce51ee9a12e523f35a3350bf859e16d06dfaa25',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.2--0.2.3.sql',
            size: 153,
            sha256:
              'a46540236f5eef0955c7b48a34c468332ffdf28242ec39e3e93ff3129e9a5d61',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.3--0.2.4.sql',
            size: 153,
            sha256:
              'def15581c900e51eab8ebde541ada84f36ba9c1c39c6e5c272d1523ed114ccdd',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.4--0.2.5.sql',
            size: 153,
            sha256:
              'bc11f67c5e2aa15709332d68d91cdfffc80189403608d7ceed2da573edd8eab8',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.5--0.2.6.sql',
            size: 153,
            sha256:
              'a9d31e2be0607f0462399e0b8f79a2e267fef8117b1c50a9e9b1c7758cd9e29a',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.6--0.2.7.sql',
            size: 153,
            sha256:
              '25cf8bc50ee366705e58fd3ccc8ea1d4069e7ad3558dd220fbe0ebc1ac28a0ff',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.7--0.3.0.sql',
            size: 153,
            sha256:
              '4edaecabf8186776e0eae84b6312885cb0c6cf4e83ae698a547e735f113231f8',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.3.0--0.3.1.sql',
            size: 153,
            sha256:
              'f6b5b78e08bd948567a0a56d7102d53b5ab1d2cde7ccf41e41bd899642406a1c',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.3.1--0.3.2.sql',
            size: 153,
            sha256:
              'd04695948d418cc70cfb688aa2e34ae83b3a7dc00ec93e5b53b0dbc3ead8c6ac',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.3.2--0.4.0.sql',
            size: 864,
            sha256:
              '5ac5156b94b840961ad6a212bc1fd4bd090c3b6948d760c221d5db469d100712',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.0--0.4.1.sql',
            size: 153,
            sha256:
              '190593e701eb39797e357aacf515ef904674e7a5eb67cda7f9dd1bf8e510439e',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.1--0.4.2.sql',
            size: 153,
            sha256:
              '7ca4a21f4bba3a9d0b2bc9d3cac1e1677be1c513ddaecc20e4f5b084cc89d2a9',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.2--0.4.3.sql',
            size: 153,
            sha256:
              '2f980ceb5fdab1b0e8e88fac0554cffce7477f82217aec66feb558a7eda9e2b9',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.3--0.4.4.sql',
            size: 153,
            sha256:
              'bef1ec174a0bbceebdf4defebbf9f7514500bfc89d44e481cdf8a2692989ca52',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.4--0.5.0.sql',
            size: 1426,
            sha256:
              '1d0b08225f08a59a78dd90e5ccd33c6f12913a51d65392c784f6907272c40292',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.5.0--0.5.1.sql',
            size: 153,
            sha256:
              '9654eb95f90ccef166e84f9991cc2ed4f50ef3f0e49bdd60860fdac9124eb1ab',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.5.1--0.6.0.sql',
            size: 243,
            sha256:
              'f75c37c441bf79d4b41766409118d519b2ed491c807636da11ecf40df87a96b8',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.6.0--0.6.1.sql',
            size: 459,
            sha256:
              '2b0c4292e217cd7fabc3b008f60728a1c5da2b55c77c12afcd96dff3243e28bd',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.6.1--0.6.2.sql',
            size: 153,
            sha256:
              '0c51abf5c5f89150a1b0ce8424a461471b8543687252cf3827c04c81d4712224',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.6.2--0.7.0.sql',
            size: 20375,
            sha256:
              '97732d03249e50f32b43ea46a81acd21f6770b65dcfeb1c45f86ce483fe8dbd6',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.0--0.7.1.sql',
            size: 153,
            sha256:
              '936696328866f90b7c9f4085b18d46f9bb938acd22ab2416ddd77650857f3dc2',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.1--0.7.2.sql',
            size: 153,
            sha256:
              'ed25b8ad8066518108c06ea80e2e931172e58aacebd024d753e0c2fb294168fa',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.2--0.7.3.sql',
            size: 153,
            sha256:
              '59507662ab28371501e610e4dffbb0588216f2e7efbdc4202212600573cc138f',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.3--0.7.4.sql',
            size: 153,
            sha256:
              '122d2985b021236c02258e3d28d9151d7eb4987ccce2875137390b5209b8c379',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.4--0.8.0.sql',
            size: 1227,
            sha256:
              '54bfa94b97113d5a2923434ca49e049dd04027a20142babeea2e6c1ae19ff157',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.8.0--0.8.1.sql',
            size: 153,
            sha256:
              '3740d7be31c57afd9e39aed6a79eb4f4ce11ed98f800279263ea84d36e59a858',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.8.1.sql',
            size: 31171,
            sha256:
              '7fb5bb279ef83bf9204bfac7405bb5c9a05e49f5ac7d64d1eb4464d103b80f32',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector.control',
            size: 145,
            sha256:
              'a0205f50f78f48402e3b5ff707a5225dd684360156ba6a591f02e9afa6a47120',
            kind: 'control',
          },
        ],
        sideModules: [
          {
            logicalName: 'vector',
            path: 'lib/postgresql/vector.so',
            sha256:
              'b96fce0b884ca5bcb85b7a2b759c2debebce760f996c3c014097c5755d96e4a2',
            wasmAbiSection: 'classic',
            importsHash:
              '16fe53d0611a8a69c087ae055b9100fd649f907599ffe82702311a2df6b9323d',
            loadAfter: [],
          },
        ],
        requiredSharedPreloadLibraries: [],
        processConfig: {
          pgliteEnv: {},
          requiredHostCapabilities: [],
        },
        capabilities: {
          directSharedMemory: false,
          backgroundWorkers: false,
          parallelWorkers: false,
        },
      },
      url: new URL('../release/vector.wasm32-classic.tar.gz', import.meta.url),
    },
    'wasm32-multi-memory': {
      targetKey: 'wasm32-multi-memory',
      target: {
        pointerWidth: 32,
        memoryAddressWidth: 32,
        topology: 'multi-memory',
        postgresMajor: 18,
        postgresAbi:
          'postgres-180003-catalog-202506291-block-8192-wal-8192-wasm32',
        pgliteExtensionAbi: 'pglite-extension-abi-v1',
        memoryAbi: 'pglite-tagged-i32-v1',
        hostAbi: 'pglite-host-abi-v1',
      },
      archiveBytes: 63843,
      archiveSha256:
        '08d18972f49171bf9b6e97a9d98e60d27d26ca74355e3bf8125175fc0112ed28',
      manifestSha256:
        '31c8d3746408c50ca2cab0cac35c4390c086d96214918711ccdce31b4cdce862',
      manifest: {
        formatVersion: 1,
        extensionName: 'vector',
        extensionVersion: '0.0.5',
        target: {
          pointerWidth: 32,
          memoryAddressWidth: 32,
          topology: 'multi-memory',
          postgresMajor: 18,
          postgresAbi:
            'postgres-180003-catalog-202506291-block-8192-wal-8192-wasm32',
          pgliteExtensionAbi: 'pglite-extension-abi-v1',
          memoryAbi: 'pglite-tagged-i32-v1',
          hostAbi: 'pglite-host-abi-v1',
        },
        artifactDependencies: [],
        postgresExtensions: [
          {
            name: 'vector',
            requires: [],
          },
        ],
        files: [
          {
            path: 'include/postgresql/server/extension/vector/halfvec.h',
            size: 2031,
            sha256:
              'f32099b56688fbae57548083a26555fafb296e0bf68430c368cf8e5d61e8daf2',
            kind: 'other',
          },
          {
            path: 'include/postgresql/server/extension/vector/sparsevec.h',
            size: 1184,
            sha256:
              'e58587d476df10bfbed2c63cfd50a91d7e8067f9d180c650b9d5990d2f6a82f6',
            kind: 'other',
          },
          {
            path: 'include/postgresql/server/extension/vector/vector.h',
            size: 825,
            sha256:
              '5dd5f55ae4dab6b950e2274ef50c69c2ddc1263f019d647630bf3bfa57f493a3',
            kind: 'other',
          },
          {
            path: 'lib/postgresql/vector.so',
            size: 182273,
            sha256:
              '58332ee9392d3dfa598c3f79bdd95fe0f9233c7bae0091e469f7ab2fbb15d584',
            kind: 'side-module',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.0--0.1.1.sql',
            size: 2047,
            sha256:
              '7b98ca899d63e8128ea3c980634b2d675e0dc6e7f27843e666d4e9980db0ab63',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.1--0.1.3.sql',
            size: 153,
            sha256:
              '57024ba8abad34b9ca151310748518b061a36e2df9b5ba0487e1cd186b1a208f',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.3--0.1.4.sql',
            size: 153,
            sha256:
              '98e7caa4958e026c56613ed779abe469adca9e5e82190d20e19aa345c5e6f71f',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.4--0.1.5.sql',
            size: 153,
            sha256:
              '3fa555492b673f9e0402fefdbd3fc0e479afb29b7141b49145bed8dc691b2c4f',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.5--0.1.6.sql',
            size: 153,
            sha256:
              '557e3d9df2b9f5a5a2428545dbcfa7d99d62f489bbd44127445a36663a8953d1',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.6--0.1.7.sql',
            size: 403,
            sha256:
              '0975ff29e6b8268382253ce0e75cc6b5364582280ef1a7b40a137ce4c6267887',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.7--0.1.8.sql',
            size: 396,
            sha256:
              'fcac329c0901fdcb1d3884e7bf8017c75632136dea88fb8b6352de7e61d4aba5',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.1.8--0.2.0.sql',
            size: 153,
            sha256:
              'ac330285f527a73d4def55b5de17eae6729a0c052139bb0345aa1a92af96d516',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.0--0.2.1.sql',
            size: 744,
            sha256:
              '0ccec7b1bc7c5e76f5da10b06713e45b08aebcdca7c833ffb4fda8f44d7ae872',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.1--0.2.2.sql',
            size: 153,
            sha256:
              '79a1492abf44c7641893b9f80ce51ee9a12e523f35a3350bf859e16d06dfaa25',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.2--0.2.3.sql',
            size: 153,
            sha256:
              'a46540236f5eef0955c7b48a34c468332ffdf28242ec39e3e93ff3129e9a5d61',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.3--0.2.4.sql',
            size: 153,
            sha256:
              'def15581c900e51eab8ebde541ada84f36ba9c1c39c6e5c272d1523ed114ccdd',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.4--0.2.5.sql',
            size: 153,
            sha256:
              'bc11f67c5e2aa15709332d68d91cdfffc80189403608d7ceed2da573edd8eab8',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.5--0.2.6.sql',
            size: 153,
            sha256:
              'a9d31e2be0607f0462399e0b8f79a2e267fef8117b1c50a9e9b1c7758cd9e29a',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.6--0.2.7.sql',
            size: 153,
            sha256:
              '25cf8bc50ee366705e58fd3ccc8ea1d4069e7ad3558dd220fbe0ebc1ac28a0ff',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.2.7--0.3.0.sql',
            size: 153,
            sha256:
              '4edaecabf8186776e0eae84b6312885cb0c6cf4e83ae698a547e735f113231f8',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.3.0--0.3.1.sql',
            size: 153,
            sha256:
              'f6b5b78e08bd948567a0a56d7102d53b5ab1d2cde7ccf41e41bd899642406a1c',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.3.1--0.3.2.sql',
            size: 153,
            sha256:
              'd04695948d418cc70cfb688aa2e34ae83b3a7dc00ec93e5b53b0dbc3ead8c6ac',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.3.2--0.4.0.sql',
            size: 864,
            sha256:
              '5ac5156b94b840961ad6a212bc1fd4bd090c3b6948d760c221d5db469d100712',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.0--0.4.1.sql',
            size: 153,
            sha256:
              '190593e701eb39797e357aacf515ef904674e7a5eb67cda7f9dd1bf8e510439e',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.1--0.4.2.sql',
            size: 153,
            sha256:
              '7ca4a21f4bba3a9d0b2bc9d3cac1e1677be1c513ddaecc20e4f5b084cc89d2a9',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.2--0.4.3.sql',
            size: 153,
            sha256:
              '2f980ceb5fdab1b0e8e88fac0554cffce7477f82217aec66feb558a7eda9e2b9',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.3--0.4.4.sql',
            size: 153,
            sha256:
              'bef1ec174a0bbceebdf4defebbf9f7514500bfc89d44e481cdf8a2692989ca52',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.4.4--0.5.0.sql',
            size: 1426,
            sha256:
              '1d0b08225f08a59a78dd90e5ccd33c6f12913a51d65392c784f6907272c40292',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.5.0--0.5.1.sql',
            size: 153,
            sha256:
              '9654eb95f90ccef166e84f9991cc2ed4f50ef3f0e49bdd60860fdac9124eb1ab',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.5.1--0.6.0.sql',
            size: 243,
            sha256:
              'f75c37c441bf79d4b41766409118d519b2ed491c807636da11ecf40df87a96b8',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.6.0--0.6.1.sql',
            size: 459,
            sha256:
              '2b0c4292e217cd7fabc3b008f60728a1c5da2b55c77c12afcd96dff3243e28bd',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.6.1--0.6.2.sql',
            size: 153,
            sha256:
              '0c51abf5c5f89150a1b0ce8424a461471b8543687252cf3827c04c81d4712224',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.6.2--0.7.0.sql',
            size: 20375,
            sha256:
              '97732d03249e50f32b43ea46a81acd21f6770b65dcfeb1c45f86ce483fe8dbd6',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.0--0.7.1.sql',
            size: 153,
            sha256:
              '936696328866f90b7c9f4085b18d46f9bb938acd22ab2416ddd77650857f3dc2',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.1--0.7.2.sql',
            size: 153,
            sha256:
              'ed25b8ad8066518108c06ea80e2e931172e58aacebd024d753e0c2fb294168fa',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.2--0.7.3.sql',
            size: 153,
            sha256:
              '59507662ab28371501e610e4dffbb0588216f2e7efbdc4202212600573cc138f',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.3--0.7.4.sql',
            size: 153,
            sha256:
              '122d2985b021236c02258e3d28d9151d7eb4987ccce2875137390b5209b8c379',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.7.4--0.8.0.sql',
            size: 1227,
            sha256:
              '54bfa94b97113d5a2923434ca49e049dd04027a20142babeea2e6c1ae19ff157',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.8.0--0.8.1.sql',
            size: 153,
            sha256:
              '3740d7be31c57afd9e39aed6a79eb4f4ce11ed98f800279263ea84d36e59a858',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector--0.8.1.sql',
            size: 31171,
            sha256:
              '7fb5bb279ef83bf9204bfac7405bb5c9a05e49f5ac7d64d1eb4464d103b80f32',
            kind: 'sql',
          },
          {
            path: 'share/postgresql/extension/vector.control',
            size: 145,
            sha256:
              'a0205f50f78f48402e3b5ff707a5225dd684360156ba6a591f02e9afa6a47120',
            kind: 'control',
          },
        ],
        sideModules: [
          {
            logicalName: 'vector',
            path: 'lib/postgresql/vector.so',
            sha256:
              '58332ee9392d3dfa598c3f79bdd95fe0f9233c7bae0091e469f7ab2fbb15d584',
            wasmAbiSection: 'pglite.multi-memory.abi',
            importsHash:
              '6b3e3e6309963f6b1bc52897ea6b4d068c4a784bb131b088e0630e55629b4cf1',
            loadAfter: [],
          },
        ],
        requiredSharedPreloadLibraries: [],
        processConfig: {
          pgliteEnv: {},
          requiredHostCapabilities: [],
        },
        capabilities: {
          directSharedMemory: true,
          backgroundWorkers: false,
          parallelWorkers: false,
        },
      },
      url: new URL(
        '../release/vector.wasm32-multi-memory.tar.gz',
        import.meta.url,
      ),
    },
  },
} as const satisfies PGliteExtensionBackendDescriptor
