#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs'

const [output, ...specifications] = process.argv.slice(2)
if (!output || specifications.length === 0) {
  throw new Error(
    'usage: pglite-generate-extension-wrapper OUTPUT TARGET=DESCRIPTOR=ARCHIVE ...',
  )
}

const entries = specifications.map((specification) => {
  const [targetKey, descriptorPath, archivePath, extra] =
    specification.split('=')
  if (!targetKey || !descriptorPath || !archivePath || extra !== undefined) {
    throw new Error(`invalid wrapper artifact specification: ${specification}`)
  }
  const external = JSON.parse(readFileSync(descriptorPath, 'utf8'))
  if (external.targetKey !== targetKey) {
    throw new Error(
      `descriptor ${descriptorPath} is ${external.targetKey}, expected ${targetKey}`,
    )
  }
  return {
    targetKey,
    descriptor: {
      targetKey: external.targetKey,
      target: external.target,
      archiveBytes: external.archiveBytes,
      archiveSha256: external.archiveSha256,
      manifestSha256: external.manifestSha256,
      manifest: external.extensionManifest,
    },
    archivePath,
  }
})

entries.sort(({ targetKey: left }, { targetKey: right }) =>
  left.localeCompare(right),
)

const body = entries
  .map(
    ({ targetKey, descriptor, archivePath }) =>
      `  ${JSON.stringify(targetKey)}: {\n${indent(
        JSON.stringify(descriptor, null, 2).slice(1, -1).trim(),
        4,
      )},\n    "url": new URL(${JSON.stringify(archivePath)}, import.meta.url)\n  }`,
  )
  .join(',\n')

const targetKeys = entries.map(({ targetKey }) => targetKey)
const releaseProfile =
  JSON.stringify(targetKeys) ===
  JSON.stringify(['wasm32-classic', 'wasm32-multi-memory'])
    ? 'wasm32-initial'
    : undefined

writeFileSync(
  output,
  `// Generated by pglite-generate-extension-wrapper. Do not edit.\n` +
    `import type { PGliteExtensionBackendDescriptor } from '@electric-sql/pglite'\n\n` +
    `export const generatedExtensionBackend = {\n` +
    (releaseProfile
      ? `  releaseProfile: ${JSON.stringify(releaseProfile)},\n`
      : '') +
    `  targetKeys: ${JSON.stringify(targetKeys)},\n` +
    `  artifacts: {\n${indent(
      body,
      4,
    )}\n  }\n} as const satisfies PGliteExtensionBackendDescriptor\n`,
)

function indent(value, spaces) {
  const prefix = ' '.repeat(spaces)
  return value
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n')
}
