name: Trigger BuildKite build of Docker image for building PGlite

on:
  push:
    branches: ['main']
    paths:
      - .buildconfig
  pull_request:
    paths:
      - .buildconfig

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build on Push using v2.0.0
        uses: buildkite/trigger-pipeline-action@v2.0.0
        with:
          buildkite_api_access_token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }}
          pipeline: 'vaxine/build-pglite-builder-docker-image'
          branch: ${{ github.head_ref || github.ref_name }}
          commit: HEAD
          message: '🚀 Triggered from a GitHub Action'
          build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
